project:
  type: website
  output-dir: docs

website:
  title: "Raunak Farhaz"
  site-url: https://raunakfarhaz.com
  favicon: images/favicon.svg
  search: false
  page-footer: $\textcopyright$ made by Raunak Farhaz | Berlin, Germany 2024
  navbar:
    title: false
    logo: images/favicon.svg
    right:
      - text: "HOME"
        href: index.qmd
      - text: "BIO"
        href: resources/cv.qmd
      - text: "RESEARCH"
        href: resources/research.qmd
      - text: "PUBLICATIONS"
        href: resources/publication.qmd
      - text: "LEARN"
        href: resources/teach.qmd
      - text: "BLOG"
        href: resources/blog.qmd   
      

format:
  html:
    theme:
        - default
        - styles.scss
    toc: true
    toc-location: right
    smooth-scroll: true
    code-fold: true
  
    

